package com.mgb.mapper;

import com.mgb.bean.Department;
import com.mgb.bean.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int updateByPrimaryKey(Department record);
}