package com.mgb.mapper;

import com.mgb.bean.Employee;
import com.mgb.bean.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab1_employee
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    int updateByPrimaryKey(Employee record);
}