package com.mgb.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab1_dept.id
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab1_dept.dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    private String dept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab1_dept.id
     *
     * @return the value of tab1_dept.id
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab1_dept.id
     *
     * @param id the value for tab1_dept.id
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab1_dept.dept
     *
     * @return the value of tab1_dept.dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab1_dept.dept
     *
     * @param dept the value for tab1_dept.dept
     *
     * @mbg.generated Sun Jan 16 12:47:48 CST 2022
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }
}